# rust driver crane outputs: package, clippy, test, deny, doctest,
# plus the example binary and a schema verification check
{
  pkgs,
  craneLib,
  src,
  cargoToml,
}: let
  crateName = craneLib.crateNameFromCargoToml {inherit cargoToml;};

  commonArgs = {
    inherit src;
    inherit (crateName) pname version;
    strictDeps = true;
  };

  cargoArtifacts = craneLib.buildDepsOnly commonArgs;

  # checked-in reference schema generated by the example binary
  referenceSchema = ../rust/example-mycel/schema.json;

  # build the example binary on its own so we can run it in the schema check
  example = craneLib.buildPackage (commonArgs
    // {
      inherit cargoArtifacts;
      pname = "example-mycel";
      cargoExtraArgs = "--bin example-mycel";
      doCheck = false;
    });
in {
  inherit cargoArtifacts example;

  package = craneLib.buildPackage (commonArgs
    // {
      inherit cargoArtifacts;
      # nextest handles tests as its own check, don't duplicate
      doCheck = false;
    });

  clippy = craneLib.cargoClippy (commonArgs
    // {
      inherit cargoArtifacts;
      cargoClippyExtraArgs = "--all-targets -- --deny warnings";
    });

  test = craneLib.cargoNextest (commonArgs
    // {
      inherit cargoArtifacts;
    });

  deny = craneLib.cargoDeny (commonArgs
    // {
      inherit cargoArtifacts;
    });

  # nextest doesn't run doctests, so cover them separately
  doctest = craneLib.cargoDocTest (commonArgs
    // {
      inherit cargoArtifacts;
    });

  # catches drift between the example Config struct and the checked-in
  # schema.json. if the struct changes, this check fails until someone
  # re-runs `cargo run -p example-mycel > rust/example-mycel/schema.json`
  schemaCheck = pkgs.runCommand "nixcfg-schema-check" {} ''
    ${pkgs.diffutils}/bin/diff -u ${referenceSchema} <(${example}/bin/example-mycel)
    touch $out
  '';
}
